### PR TITLE
dependencies: use latest nunjucks - resolves #42

### LINKED ISSUE #42: Update to nunjucks 2
I tested the module with `nunjucks@2.3.0` and it works fine, I think it's time to update to new nunjucks.

+ I suggest using dynamic dependency definition for the latest version so you don't have to manually change it unless it's broken (there will be issues for that).

### PR DESCRIPTION
**Pull request by mdibaiee**

### CODE REVIEW

**Comment by vitkarpov** [comment]
:+1: Cool, thanks!

**Comment by mrhyde** [comment]
Thank you for integrating this epic example of "bad practice" and breaking most of the existing project using `grunt-nunjucks-2-html` that are following semver convention.
`>=` stands for "greater than or equal to" and will use most updated version *major* including! Any amount of major versions!

**Comment by mdibaiee** [comment]
@mrhyde Thanks for showing a communication "bad practice". I could come and complain in the first place because of the upper limit to a specific minor version, but I didn't and created a pull-request. Now you can do the same and save us some time by not starting an argument. Thanks.

**Comment by ArmorDarks** [comment]
@mdibaiee Well, he explained why it was unwise to merge this PR to prevent further expansion of this bad practice and made [PR](https://github.com/vitkarpov/grunt-nunjucks-2-html/pull/48) with fix. I don't see anything wrong with it.

**Comment by mrhyde** [comment]
@mdibaiee no offense but I'm not sure that you understand how semver works. Caret operator actually has no limitations on **minor** version see [doc](https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004) which means that your PR doesn't fix anything but actually breaks things

**Comment by mdibaiee** [comment]
@mrhyde I don't remember what the problem was at the time I created this pull-request so I can't really discuss it, and yes, from the docs, it seems it shouldn't have any effects, but it did.

@ArmorDarks pull-requests are great, they are helpful and now I'm grateful for that, but I don't see the point in the comment here.

**Comment by mrhyde** [comment]
It's ok. I fixed it now.

**Pull request merged**
