### PR TITLE
Added filters option

### PR DESCRIPTION
**Pull request by posabsolute**
This pull request add the ability to setup filters

### CODE REVIEW

**Comment by vitkarpov** [comment]
Maybe you can use [`configureEnvironment` options](https://github.com/vitkarpov/grunt-nunjucks-2-html#configureenvironment)? It has been added not so long time ago. Check this out:

```
{
  options: {
    configureEnv: function(env) {
       // here you can use any API provided by nunjucks' environment object
       env.addFilter(...)
    }
  }
}
```

**Comment by vitkarpov** [comment]
Such [issue](https://github.com/vitkarpov/grunt-nunjucks-2-html/issues/10) has been already appeared. Also there was a request to adding global vars for every template, so I decided to provide an ability to configure environment before templates` processing.

**Comment by posabsolute** [comment]
Ah! Great, I somehow missed configureEnvironment

**Comment by vitkarpov** [comment]
Cool :+1:

**Comment by posabsolute** [comment]
Would you consider passing back options back in  configureEnvironment? this is needed in my use case

**Comment by vitkarpov** [comment]
Do you mean to pass options as an argument to `configureEnviroment` [here](https://github.com/vitkarpov/grunt-nunjucks-2-html/blob/master/tasks/nunjucks.js#L33) ?

I think we could to bind function to the task context (`this` for `registerMultiTask` callback), so you could just call `this.options()` inside `configureEnvironment` to get options. I think it could be useful for some cases.

Does it suit for you?

**Comment by posabsolute** [comment]
That would be perfect

**Pull request closed without merging**
