### PR TITLE
Improve and update `packages.json`

### PR DESCRIPTION
**Pull request by ArmorDarks**
* Moved `peerDependency` into `devDependency`, since `peerDependency` depreciated
* Moved `lodash` to `dependencides` — it's needed for production, not only for development
* Proper format for `license`
* Updated dependencies' versions
* A bit more meaningful order of properties

### CODE REVIEW

**Comment by ArmorDarks** [comment]
I propose to drop license's filename, otherwise we have to use literally that value:

```
"license": "SEE LICENSE IN <LICENSE>",
```

In all other cases npm will report error during parsing `license`, since he strongly ensured that MIT is standard license and there is no need to point to local file manually: https://docs.npmjs.com/files/package.json#license

**Comment by vitkarpov** [comment]
Drop license — +1

**Comment by vitkarpov** [comment]
Please, remove `lodash` from dependencies. I'm about to remove `cloneDeep` 'cause of performance issues you've pointed.

**Comment by vitkarpov** [comment]
let's fix the latter and :+1:

**Comment by ArmorDarks** [comment]
done, but there will be conflict with 49fcaf76fed59d0dfb829d2b59e70372ec2b5f72 anyway which must be resolved manually

**Comment by vitkarpov** [comment]
done

**Pull request merged**
